# Project information
site_name: 'Documentation - GreedyGame'
site_author: 'GreedyGame'
site_url: 'https://docs.greedygame.com'
google_analytics:
  - UA-135337269-5
  - auto

# Copyright
copyright: 'Copyright &copy; 2019 GreedyGame Media Pvt Ltd'

# Navigations
nav:
  - Get Started: 
    - index.md
    # - iOS: ios.md
    # - Unity: unity.md
  - FAQs:
    - General: general-faq.md
    - Financial: financial-faq.md
    - Legal: legal-faq.md
    - Dashboard: dashboard-faq.md
    - Ad Unit Placement: adunit-faq.md
    - Android: android-faq.md
    - iOS: ios-faq.md
    - Unity: unity-faq.md
  - Android:
    - Add New App : New01_add_app.md
    - Add Ad Unit : New08_add_ad_unit.md
    - Import SDK : New03_import_sdk.md
    - Add Dependencies : New04_add_dependencies.md
    - Update Android Manifest : New05_update_manifest.md
    - Add Permissions : New06_add_permissions.md
    - Add ClearText Traffic Support : New07_cleartext_traffic_support.md
    - Initialize GreedyGameAgent : New09_initialize_greedygameagent.md
    - Enable Admob : New13_admob.md
    - Rendering Native Ads : New11_rendering_ads.md
    - Refresh Ads : New12_refresh_ads.md
    - Enable GDPR Compliance : New14_gdpr_compliance.md
    - Enable COPPA Compliance : New15_coppa_compliance.md
    - Test Ads : New16_test_ads.md
  - iOS:
    - SDK-8 series : ios-advanced.md
  - Unity:
    - SDK-8 Series:  unity-advanced.md
  - Sample Projects:
    - Download Sample Projects : sample_project.md
  - Support: 
    - support.md
  - Beta Version:
    - Android SDK-9 Beta: android.md
    - iOS SDK-9 Beta: iOS-9.0.md
    - Unity SDK-9 Beta: unity.md
  





# configuration
theme: 
  name: material
  palette:
    primary: 'Teal'
    accent: 'Amber'
  logo:
    icon: 'cloud'
  feature:
    tabs: true

extra_css: 
  [
    css/extra.css,
    css/material-button.css
  ]
  
extra_javascript:
  [
    js/external.js
  ]

#repo_name: 'greedygame/android-sdk'
#repo_url: 'https://github.com/GreedyGame/android-native-plugin'

# extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences