# Project information
site_name: 'Documentation - GreedyGame'
site_author: 'GreedyGame'
site_url: 'https://docs.greedygame.com'
google_analytics:
  - UA-135337269-5
  - auto

# Copyright
copyright: 'Copyright &copy; 2019 GreedyGame Media Pvt Ltd'

# Navigations
nav:
  - Get Started: 
    - index.md
  - Best Practices:
    - best-practices.md
    - Best Practices - Apps : apps-best-practices.md
    - Best Practices - Games : games-best-practices.md
    # - iOS: ios.md
    # - Unity: unity.md
  - FAQs:
    - General: general-faq.md
    - Financial: financial-faq.md
    - Legal: legal-faq.md
    - Dashboard: dashboard-faq.md
    - Ad Unit Placement: adunit-faq.md
    - Android: android-faq.md
    - iOS: ios-faq.md
    - Unity: unity-faq.md
  - Android:
    - Add New App : android-start.md
    - Add Ad Unit : android-add-ad-unit.md
    - Import SDK : android-import-sdk.md
    - Add Dependencies : android-add-dependencies.md
    - Update Android Manifest : android-update-manifest.md
    - Add Permissions : android-add-permissions.md
    - Add ClearText Traffic Support : android-cleartext-traffic.md
    - Initialize GreedyGameAgent : android-initialize-greedygameagent.md
    - Enable Admob : android-admob.md
    - Rendering Native Ads : android-rendering-ads.md
    - Refresh Ads : android-refresh-ads.md
    - Enable GDPR Compliance : android-gdpr-compliance.md
    - Enable COPPA Compliance : android-coppa-compliance.md
    - Test Ads : android-test-ads.md
  - iOS:
    - SDK-8 series : ios-advanced.md
  - Unity:
    - SDK-8 Series:  unity-advanced.md
  - Sample Projects:
    - Download Sample Projects : sample_project.md
  - Support: 
    - support.md
  - Beta Version:
    - Android SDK-9 Beta: android.md
    - iOS SDK-9 Beta: iOS-9.0.md
    - Unity SDK-9 Beta: unity.md
  





# configuration
theme: 
  name: material
  palette:
    primary: 'Teal'
    accent: 'Amber'
  logo:
    icon: 'cloud'
  feature:
    tabs: true

extra_css: 
  [
    css/extra.css,
    css/material-button.css
  ]
  
extra_javascript:
  [
    js/external.js
  ]

#repo_name: 'greedygame/android-sdk'
#repo_url: 'https://github.com/GreedyGame/android-native-plugin'

# extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences