# Project information
site_name: 'Documentation - GreedyGame'
site_author: 'GreedyGame'
site_url: 'https://docs.greedygame.com'
google_analytics:
  - UA-135337269-5
  - auto

# Copyright
copyright: 'Copyright &copy; 2019 GreedyGame Media Pvt Ltd'

# Navigations
nav:
  - Get Started: 
    - index.md
  - Best Practices:
    - best-practices.md
    - Best Practices - Apps : apps-best-practices.md
    - Best Practices - Games : games-best-practices.md
    # - iOS: ios.md
    # - Unity: unity.md
  - FAQs:
    - General: general-faq.md
    - Financial: financial-faq.md
    - Legal: legal-faq.md
    - Dashboard: dashboard-faq.md
    - Ad Unit Placement: adunit-faq.md
    - Android: android-faq.md
    - iOS: ios-faq.md
    - Unity: unity-faq.md
  - Android:
    - Add New App : android-start.md
    - Add Ad Unit : android-add-ad-unit.md
    - SDK Version 8.8.17:
      - Import SDK : 8-8-17/android/android-import-sdk.md
      - Add Dependencies : 8-8-17/android/android-add-dependencies.md
      - Update Android Manifest : 8-8-17/android/android-update-manifest.md
      - Add Permissions : 8-8-17/android/android-add-permissions.md
      - Support for User Certificates : 8-8-17/android/android-cleartext-traffic.md
      - Initialize GreedyGameAgent : 8-8-17/android/android-initialize-greedygameagent.md
      - Enable Admob : 8-8-17/android/android-admob.md
      - Enable Facebook : 8-8-17/android/android-fan.md
      - Enable MoPub : 8-8-17/android/android-mopub.md
      - Rendering Native Ads : 8-8-17/android/android-rendering-ads.md
      - Refresh Ads : 8-8-17/android/android-refresh-ads.md
      - Enable GDPR Compliance : 8-8-17/android/android-gdpr-compliance.md
      - Enable COPPA Compliance : 8-8-17/android/android-coppa-compliance.md
      - Enable CCPA Compliance : 8-8-17/android/android-ccpa-compliance.md
      - Test Ads : 8-8-17/android/android-test-ads.md
    - SDK Version 8.8.16:
      - Import SDK : android-import-sdk.md
      - Add Dependencies : android-add-dependencies.md
      - Update Android Manifest : android-update-manifest.md
      - Add Permissions : android-add-permissions.md
      - Add ClearText Traffic Support : android-cleartext-traffic.md
      - Initialize GreedyGameAgent : android-initialize-greedygameagent.md
      - Enable Admob : android-admob.md
      - Rendering Native Ads : android-rendering-ads.md
      - Refresh Ads : android-refresh-ads.md
      - Enable GDPR Compliance : android-gdpr-compliance.md
      - Enable COPPA Compliance : android-coppa-compliance.md
      - Test Ads : android-test-ads.md
  - iOS:
    - Add New App : ios-start.md
    - Add Ad unit : ios-add-ad-unit.md
    - SDK Version 8.8.17:
      - Import SDK : 8-8-17/iOS/ios-import-sdk.md
      - Add Permissions : 8-8-17/iOS/add-ios-permissions.md
      - Initialize GreedyGameAgent : 8-8-17/iOS/ios-initialize-greedygameagent.md
      - Enable Admob : 8-8-17/iOS/ios-admob.md
      - Enable MoPub : 8-8-17/iOS/ios-moPub.md
      - Rendering Native Ads : 8-8-17/iOS/ios-rendering-ads.md
      - Refresh Ads : 8-8-17/iOS/ios-refresh-ads.md
      - Enable GDPR Compliance : 8-8-17/iOS/ios-gdpr-compliance.md
      - Enable COPPA Compliance : 8-8-17/iOS/ios-coppa-compliance.md
      - Enable CCPA Compliance : 8-8-17/iOS/ios-ccpa-compliance.md
      - Test Ads : 8-8-17/iOS/ios-test-ads.md
    - SDK Version 8.8.16:
      - Import SDK : ios-import-sdk.md
      - Add Permissions : 8-8-17/iOS/add-ios-permissions.md
      - Initialize GreedyGameAgent : ios-initialize-greedygameagent.md
      - Enable Admob : ios-admob.md
      - Rendering Native Ads : ios-rendering-ads.md
      - Refresh Ads : ios-refresh-ads.md
      - Enable GDPR Compliance : ios-gdpr-compliance.md
      - Enable COPPA Compliance : ios-coppa-compliance.md
      - Test Ads : ios-test-ads.md
  - Unity:
    - SDK-8 Series:  unity-advanced.md
  - Sample Projects:
    - Download Sample Projects : sample_project.md
  - Support: 
    - support.md
  - Beta Version:
    - Android SDK-9 Beta: android.md
    - iOS SDK-9 Beta: iOS-9.0.md
    - Unity SDK-9 Beta: unity.md
  - Developer Reference: 
    - Android: 
      - android-method-reference.md
      - GreedyGameAgent : android-method-reference/#greedygameagent
      - GreedyGameBuilder : android-method-reference/#greedygamebuilder





# configuration
theme: 
  name: material
  palette:
    primary: 'Teal'
    accent: 'Amber'
  logo:
    icon: 'cloud'
  feature:
    tabs: true

extra_css: 
  [
    css/extra.css,
    css/material-button.css
  ]
  
extra_javascript:
  [
    js/external.js
  ]

#repo_name: 'greedygame/android-sdk'
#repo_url: 'https://github.com/GreedyGame/android-native-plugin'

# extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences